### ISSUE TITLE
Published .pom file checksums appear to be invalid.

### ISSUE THREAD

**Issue by easel** [OpenHFT/OpenHFT#15]
I ran into an issue resolving dependencies for my project using coursier and we tracked down the issue to the fact that apparently the third-party-bom .pom file for openhft isn't being checksummed properly.

```
$ wget https://repo1.maven.org/maven2/net/openhft/third-party-bom/3.4.20/third-party-bom-3.4.20.pom
$ wget https://repo1.maven.org/maven2/net/openhft/third-party-bom/3.4.20/third-party-bom-3.4.20.pom.sha1
$ cat third-party-bom-3.4.20.pom.sha1
a55111b4fbbd40553d263f664978c6ea9f9b96ed
$ shasum third-party-bom-3.4.20.pom
995544ef2c57264c49e5fbd03307ebeebc5a47da  third-party-bom-3.4.20.pom
```

I assume maven mustn't check the signatures on .pom files or something, because resolution seems to work fine from there.

**Comment by peter-lawrey** [comment]
Can you try the 3.5.0 version of the pom?

**Comment by easel** [comment]
```

**Comment by peter-lawrey** [comment]
They are all using 3.5.1, soon to be 3.5.2 of the third party bom.
