### ISSUE TITLE
Xstream 4.8 -> 4.9

### ISSUE THREAD

**Issue by lesserwhirls** [OpenHFT/OpenHFT#16]
Greetings!

I was wondering if there has been any discussion of bumping `XStream` from version 4.8 to 4.9? It does not look like there were any API changes that would impact anything relying on the `third-party-bom` (that is, nothing was removed).

http://x-stream.github.io/changes.html#4.9

A project I work on uses chronicle-map, and one of our users pointed out an issue in 4.8.

Thanks!

**Comment by RobAustin** [comment]
yes - I'll see if we can do this.

**Comment by RobAustin** [comment]
I've just released 3.5.9 of the  third-party-bom which has the latest Stream

**Comment by lesserwhirls** [comment]
Thanks @RobAustin!
