### ISSUE TITLE
remove old check.thread.safety property

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/OpenHFT#194]
https://github.com/search?q=org%3AOpenHFT%20check.thread.safety&type=code

Use of this property was removed a while ago so we should remove it from `system.properties`, doco etc

**Comment by david-ry4n** [comment]
Created branch 'remove-old-check-thread-safety-property' PRs 

GitHub search:  (org:OpenHFT OR org:ChronicleSoftware OR org:ChronicleEnterprise) AND NOT is:archived  check.thread.safety

- [x] https://github.com/OpenHFT/Chronicle-Queue/pull/1584
- [x] https://github.com/OpenHFT/Chronicle-Map/pull/542
- [x] https://github.com/OpenHFT/Chronicle-Bytes/pull/635
- [x] https://github.com/OpenHFT/Chronicle-Wire/pull/901
- [x] https://github.com/OpenHFT/Chronicle-Threads/pull/256
- [x] https://github.com/OpenHFT/Chronicle-Values/pull/51

**Comment by david-ry4n** [comment]
A few more..
- [x] https://github.com/OpenHFT/OpenHFT/pull/233
- [x] https://github.com/OpenHFT/Chronicle-Queue-Demo/pull/39
- [x] https://github.com/OpenHFT/Chronicle-Decentred/pull/9
- [x] https://github.com/ChronicleSoftware/Chronicle-EFX-Demo/pull/34

**Comment by david-ry4n** [comment]
- [x] https://github.com/ChronicleSoftware/Chronicle-Channel/pull/1

Unable to write to 
https://github.com/ChronicleSoftware/Legecy-Chronicle-Crypto-Adapters-Demo
