### ISSUE TITLE
Add support for GraalVM

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/OpenHFT#22]
The GraalVM looks like powerful way to resolve some of the issues we have had with the JIT. If we support Java 11 I think we really want to support the GraalVM as well.

https://www.graalvm.org/docs/reference-manual/languages/jvm/

Peter.

**Comment by dpisklov** [comment]
Chronicle 3 now runs on GraalVM 1.0 RC9 (based on OpenJDK Java 8u192)
