### ISSUE TITLE
How To Replicate Sequence Number to Disaster Recovery?

### ISSUE THREAD

**Issue by btzq** [OpenHFT/OpenHFT#227]
Sequence number typically written in logs in the local server. 

Is there a built in solution in Chronicle to replicate the logs to Disaster Recovery for seamless failover?

**Comment by tgd** [comment]
Hi @btzq - our Chronicle Queue Enterprise product provides Queue replication - https://chronicle.software/queue-enterprise/ which can help you with this.

If you'd like to learn more please contact us here: https://chronicle.software/contact-us/

**Comment by btzq** [comment]
Does this mean that the proposed solution for Chronicle is have the Chronicle FIX write the sequence number to the Chronicle Queue? 

Is there a .NET version of these? Our FIX Gateway applications are written in .net

**Comment by tgd** [comment]
Hi @btzq - it really depends what problem you are trying to solve but we also offer a low latency FIX engine - Chronicle FIX. 

We currently do not offer .NET bindings however we do offer C++ and if you would like to explore support in .NET we can offer custom consultancy to understand how to best help you. If you'd like to learn more please contact us here: https://chronicle.software/contact-us/ and let me know when you've done so and we can set up some time to talk.

**Comment by tgd** [comment]
Hi, we are going to close this question out now, if you have further enquiries please let us know.
