### ISSUE TITLE
Quick Start - masters student

### ISSUE THREAD

**Issue by andrewcz** [OpenHFT/OpenHFT#25]
Hi!
Really interested in the project.
Is there a quick start guide on simulated market data?
Many thanks,
Best,
Andrew

**Comment by dpisklov** [comment]
It depends which project you are interested in. Chronicle-Map and Chronicle-Queue are fairly well documented, some others ma be a bit less so.
In any case, please do not use github issues for questions - stackoverflow is right place to get answers if you are stuck.
