### ISSUE TITLE
Hi OpenHFT team ... would it be ok if I used 'gitHub issues' ....

### ISSUE THREAD

**Issue by Cotton-Ben** [OpenHFT/OpenHFT#29]

**Comment by Cotton-Ben** [comment]
... as a mechanism to post general community style musings and questions?  I am currently on a client assignment that restricts developer write-access to StackOverflow, GoogleGroups, Gitter, etc.   Keep up great work. -Ben

**Comment by RobAustin** [comment]
Ok

**Comment by RobAustin** [comment]
Actually maybe best to email me directly.

**Comment by Cotton-Ben** [comment]
Thanks Rob.

**Comment by Cotton-Ben** [comment]
Rob, forgive me. I need to learn Chronicle XCL quickly.  emailing you now.

**Comment by RobAustin** [comment]
Ok

**Comment by RobAustin** [comment]
For information on http://www.chronicle-accelerate.com/, its best to contact Peter. I recently have been focusing on other projects so don’t have huge knowledge of XCL.

**Comment by Cotton-Ben** [comment]
Thanks Rob.
