### ISSUE TITLE
Investigate dropping log4j support.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/OpenHFT#33]
It was last released in 2012.

https://github.com/OpenHFT/OpenHFT/network/alert/third-party-bom/pom.xml/log4j:log4j/open

**Comment by JerryShea** [comment]
and replace with log4j2?

**Comment by RobAustin** [comment]
Why don't we just replace the use of log4j with "JVM.warn()" this way we are not reliant on third-party libraries?

**Comment by JerryShea** [comment]
We only depend on slf4j, which is pretty lightweight and very much a standard in the Java world. 

The problem with using Jvm.debug & warn is that in some places (Chronicle Queue Enterprise replication springs to mind) we need log.info messages. Maybe in our low level libraries we should only use Jvm.debug|warn ?

**Comment by minborg** [comment]
I think it is highly desirable to have a pluggable/configurable logging system. For example, customers may want to tee off logs to a centralized aggregated logging system and/or react to certain log messages, put log messages in databases for off-line analysis, have a specific log format (time format, severity markers etc).

**Comment by glukos** [comment]
Closing this as found no viable log4j dependecies except for chronicle-logger and CQE load harness
