### ISSUE TITLE
Bump log4j versions in third party bom to mitigate log4shell

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/OpenHFT#64]
no Chronicle products depend on log4j, but we thought it prudent to bump the versions in this bom to ensure that anyone getting their versions from this would not pick up a known insecure version of log4j.

I expect we should be able to release third-party-bom 3.22.4 in the next day or two.

**Comment by helper2424** [comment]
Вт, 21 дек. 2021 г. в 08:13, Jerry Shea ***@***.***>:
