### ISSUE TITLE
latest code build error - IO Error resolving artifact

### ISSUE THREAD

**Issue by shadowleaves** [OpenHFT/OpenHFT#7]
[INFO] OpenHFT/Java-Thread-Affinity/affinity-test ........ FAILURE [11.428s]

Tests in error: 
  OSGiBundleTest.checkBundleState » IO Error resolving artifact net.openhft:affi...
  OSGiBundleTest.checkBundleExports » IO Error resolving artifact net.openhft:af...
  OSGiBundleTest.checkInject » IO Error resolving artifact net.openhft:affinity:...

**Comment by peter-lawrey** [comment]
Closing as this is an old issue, please raise a new one if this is still a problem.
